# Generated by Django 4.2.9 on 2025-05-19 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('publico', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sugestao',
            options={'verbose_name_plural': 'Sugestões'},
        ),
    ]
