# Generated by Django 4.2.9 on 2024-09-24 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
