# Generated by Django 4.2.9 on 2024-09-25 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0002_alter_produto_estoque'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caixa',
            old_name='caixa',
            new_name='nome',
        ),
    ]
