# Generated by Django 4.2.9 on 2024-09-25 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0003_rename_caixa_caixa_nome'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ficha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.IntegerField()),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
        migrations.AddField(
            model_name='movimentacaoestoque',
            name='caixa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='movimentacao.caixa'),
        ),
    ]
