# Generated by Django 4.2.9 on 2024-09-26 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0005_alter_movimentacaoestoque_caixa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='numero',
            field=models.IntegerField(unique=True),
        ),
    ]
