# Generated by Django 4.2.9 on 2024-09-26 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0006_alter_ficha_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ficha',
            name='numero',
            field=models.PositiveSmallIntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='ficha',
            name='saldo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='produto',
            name='estoque',
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
    ]
