# Generated by Django 4.2.9 on 2024-09-26 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0008_alter_movimentacaoestoque_quantidade_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='caixa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='movimentacao.caixa'),
            preserve_default=False,
        ),
    ]
