# Generated by Django 4.2.9 on 2024-10-30 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0012_alter_ficha_saldo_alter_produto_preco'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='unidade',
            new_name='medida',
        ),
        migrations.AlterField(
            model_name='venda',
            name='movimentacao',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='movimentacao.movimentacaoestoque'),
        ),
    ]
