# Generated by Django 4.2.9 on 2025-05-19 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0013_rename_unidade_produto_medida_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movimentacaoestoque',
            options={'verbose_name_plural': 'Movimentações estoque'},
        ),
        migrations.AddField(
            model_name='produto',
            name='categoria',
            field=models.CharField(choices=[('bebidas', 'Bebidas'), ('doces', 'Doces'), ('salgados', 'Salgados'), ('jogos', 'Jogos')], default='doces', help_text='Categoria do produto', max_length=20),
        ),
    ]
