# Generated by Django 4.2.9 on 2025-11-05 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0016_reserva_antecipada'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qrcodereservaprodutosdisponiveis',
            name='produto',
        ),
        migrations.RemoveField(
            model_name='qrcodereservaprodutosdisponiveis',
            name='qrcodereserva',
        ),
        migrations.AlterModelOptions(
            name='caixa',
            options={'verbose_name_plural': 'Caixas'},
        ),
        migrations.RenameIndex(
            model_name='ficha',
            new_name='movimentaca_qr_code_d14ee0_idx',
            old_name='movimentac_qr_code_idx',
        ),
        migrations.RenameIndex(
            model_name='qrcodereserva',
            new_name='movimentaca_codigo_44377f_idx',
            old_name='movimentac_codigo_ativo_idx',
        ),
        migrations.RenameIndex(
            model_name='reservaproduto',
            new_name='movimentaca_ficha_i_49987d_idx',
            old_name='movimentac_ficha_i_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reservaproduto',
            new_name='movimentaca_produto_e761ed_idx',
            old_name='movimentac_produto_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reservaproduto',
            new_name='movimentaca_cpf_b183b2_idx',
            old_name='movimentac_cpf_status_idx',
        ),
        migrations.RenameIndex(
            model_name='reservaproduto',
            new_name='movimentaca_qr_code_6be77c_idx',
            old_name='movimentac_qr_code_status_idx',
        ),
        migrations.AddField(
            model_name='caixa',
            name='senha',
            field=models.CharField(blank=True, help_text='Senha (armazenada em texto simples - NÃO recomendado para produção)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='caixa',
            name='usuario',
            field=models.CharField(blank=True, help_text='Usuário para login do caixa', max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='qrcodereserva',
            name='produtos_disponiveis',
            field=models.ManyToManyField(blank=True, related_name='qr_codes_reserva', to='movimentacao.produto'),
        ),
        migrations.AddIndex(
            model_name='caixa',
            index=models.Index(fields=['usuario'], name='movimentaca_usuario_a1d558_idx'),
        ),
        migrations.DeleteModel(
            name='QRCodeReservaProdutosDisponiveis',
        ),
    ]
