# Generated by Django 4.2.9 on 2025-11-05 01:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0017_remove_qrcodereservaprodutosdisponiveis_produto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ficha',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ficha',
            name='deleted_by_caixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='fichas_deletadas', to='movimentacao.caixa'),
        ),
    ]
