# Generated by Django 4.2.9 on 2025-11-05 01:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0018_ficha_deleted_at_ficha_deleted_by_caixa'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='ficha',
            name='movimentaca_qr_code_d14ee0_idx',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='ficha',
            name='qr_code_generated_at',
        ),
    ]
