# Generated by Django 4.2.9 on 2025-11-05 03:29

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0019_remove_ficha_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Recarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, help_text='Valor da recarga', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('data', models.DateTimeField(auto_now_add=True, help_text='Data e hora da recarga')),
                ('observacoes', models.TextField(blank=True, help_text='Observações sobre a recarga')),
                ('caixa', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recargas', to='movimentacao.caixa')),
                ('ficha', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recargas', to='movimentacao.ficha')),
                ('produto', models.ForeignKey(blank=True, help_text='Produto relacionado à recarga (opcional)', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='recargas', to='movimentacao.produto')),
            ],
            options={
                'verbose_name_plural': 'Recargas',
                'ordering': ['-data'],
                'indexes': [models.Index(fields=['ficha', 'data'], name='movimentaca_ficha_i_0414ea_idx'), models.Index(fields=['caixa', 'data'], name='movimentaca_caixa_i_79455e_idx'), models.Index(fields=['produto', 'data'], name='movimentaca_produto_6a9f34_idx')],
            },
        ),
    ]
