# Generated by Django 4.2.9 on 2025-11-05 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movimentacao', '0020_recarga'),
    ]

    operations = [
        migrations.AddField(
            model_name='qrcodereserva',
            name='data_inicio',
            field=models.DateTimeField(blank=True, help_text='Data e hora de início da reserva', null=True),
        ),
        migrations.AlterField(
            model_name='qrcodereserva',
            name='data_expiracao',
            field=models.DateTimeField(blank=True, help_text='Data e hora de expiração/fim da reserva', null=True),
        ),
    ]
