# Generated by Django 4.2.9 on 2026-05-05 22:32

from django.db import migrations, models


def populate_password_hashes_and_sale_values(apps, schema_editor):
    Caixa = apps.get_model("movimentacao", "Caixa")
    Venda = apps.get_model("movimentacao", "Venda")

    from django.contrib.auth.hashers import identify_hasher, make_password

    for caixa in Caixa.objects.exclude(senha__isnull=True).exclude(senha=""):
        try:
            identify_hasher(caixa.senha)
        except ValueError:
            caixa.senha = make_password(caixa.senha)
            caixa.save(update_fields=["senha"])

    vendas = Venda.objects.select_related("movimentacao__produto")
    for venda in vendas:
        if venda.valor_unitario is None:
            venda.valor_unitario = venda.movimentacao.produto.preco
        if venda.valor_total is None:
            venda.valor_total = venda.valor_unitario * venda.movimentacao.quantidade
        venda.save(update_fields=["valor_unitario", "valor_total"])


class Migration(migrations.Migration):

    dependencies = [
        ("movimentacao", "0021_add_data_inicio_qrcode_reserva"),
    ]

    operations = [
        migrations.AddField(
            model_name="venda",
            name="valor_total",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AddField(
            model_name="venda",
            name="valor_unitario",
            field=models.DecimalField(
                blank=True, decimal_places=2, editable=False, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="caixa",
            name="senha",
            field=models.CharField(
                blank=True,
                help_text="Senha armazenada com hash",
                max_length=255,
                null=True,
            ),
        ),
        migrations.RunPython(
            populate_password_hashes_and_sale_values,
            migrations.RunPython.noop,
        ),
    ]
